name: app_01
description: A new Flutter application.

dependencies:
  url_launcher: ^3.0.3

  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

  flutter:
    sdk: flutter

# dependencies will want to use in the code
  cupertino_icons: ^0.1.2

# We need to development
dev_dependencies:
  build_runner: '>=0.9.0 <0.11.0'
  built_value_generator: ^6.1.2

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
